# Generated by Django 5.2.8 on 2025-11-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_collection_image_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
