# Generated by Django 5.2.8 on 2025-12-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_orderitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_one_of_one',
            field=models.BooleanField(default=False),
        ),
    ]
